services:
  # 1. Serviço MLflow UI - Usando a imagem oficial do GHCR
  mlflow-ui:
    image: ghcr.io/mlflow/mlflow:v3.4.0
    
    ports:
      - "5000:5000"
    volumes:
      # Monta o diretório local 'mlruns' para armazenar artefatos
      - ./data/mlruns:/home/kedro/data/mlruns
    
    # Comando para iniciar o servidor MLflow, apontando para o volume montado
    command: >
      mlflow ui
      --host 0.0.0.0
      --backend-store-uri file:/home/kedro/data/mlruns
    restart: always 

  # 2. Serviço Pipeline Kedro - Executa o pipeline
  kedro-run:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Monta o diretório local 'mlruns' para que o Kedro possa registrar nele
      - ./data/mlruns:/home/kedro/data/mlruns
      - .:/home/kedro 
    environment:
      # DEVE corresponder ao URI de tracking no conf/local/mlflow.yml
      - MLFLOW_TRACKING_URI=file:/home/kedro/data/mlruns
    
    command: ["kedro", "run"]
    
    depends_on:
      - mlflow-ui