feature_target: rating_average

inference:
  output_column: prediction


features:
  - min_players
  - max_players
  - play_time
  - complexity_average

split:
  test_size: 0.2
  random_state: 42

model:
  type: LinearRegression
